# -*- coding: utf-8 -*-
"""area_pi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJBcT4I2-ej90MnCr_L5P0xH7R7ToKU8
"""

import matplotlib.pyplot as plt
#import matplot
import numpy as np

# plot.style.use('classic')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

print("Escriba la cantidad de puntos que desea usar")
Cantidad = input()

# Creamos valores aleatorios para (x,y)
  x = np.random.random_sample(int(Cantidad))
  y = np.random.random_sample(int(Cantidad))
  color = ['Red','Green','blue']
  c = []
  # Multiplicamos los valores X2
  x = (x * 2) - 1
  y = (y * 2) - 1

ci = 0
ce = 0
xi = []
yi = [] 
xe = []
ye = [] 
for i in range(len(x)):
  z = (x[i]**2+y[i]**2)
  if z < 1: 
    ci = ci + 1
    c[i] = color[1] 
    xi.append(x[i])
    yi.append(y[i])
  elif z > 1:
    ce = ce + 1
    c[i] = color[0]
    xe.append(x[i])
    ye.append(y[i])
  else
    cp[i] = color[2]

vpi = (ci/ce)
print('El valor de pi es: /n',vpi)

r = 1
  n = 100
  c = np.linspace(0,2 * np.pi,n+1)
  cx = r*np.cos(c)
  cy = r*np.sin(c)

plt.ylim(-1,1)
  plt.xlim(-1,1)
  
  plt.scatter(xi,yi,color = 'green')
  plt.scatter(xe,ye,color = 'red')
  plt.plot(cx,cy, color = 'blue')
  # plt.figure(figsize=(8,8))
  # plt.set_size_inches(10.5, 10.5)
  plt.show()